export const ACCESS_TOKEN = "ACCESS_TOKEN";
export const USER_TOKEN = "USER_TOKEN";

export const CART_TOKEN = "CART_TOKEN";

export const DISCOUNT_PERCENT_TOKEN = "DISCOUNT_PERCENT_TOKEN";

export const IRRITATION_TIME_TOKEN = "IRRITATION_TIME_TOKEN";

export const VISITED_HOMEPAGE_TOKEN = "VISITED_HOMEPAGE_TOKEN";
export const INTRO_DONE_TOKEN = "INTRO_DONE_TOKEN";
